### PR TITLE
Added EKM Client

### PR DESCRIPTION
**Pull request by dymanuel**
EKM Client enables stand-alone testing and debugging of a Dyadic-based
application

### CODE REVIEW

**Comment by dymanuel** [comment]
I added a new item to the sidebar, that does not show on the page.

See: https://github.com/pivotal-cf/docs-dyadic-service-broker/blob/master/docs-book/master_middleman/source/subnavs/dyadic-service-broker_subnav.erb 

for the intended content of the sidebar. I probably missed something, though my local version works as intended. Please advice

**Comment by jncd** [comment]
Hi @dymanuel Ah, yes. That subnav file in the docs-dyadic-service-broker repo is just a helpful thing for building and reviewing the "book" on your local machine. The actual subnav for the doc lives here: https://github.com/pivotal-cf/docs-book-partners/tree/master/master_middleman/source/subnavs
I merged your PR from yesterday, but of course that didn't affect the published subnav. When I circled back to review in the late afternoon, I saw that you'd intended to change the subnav so I edited the actual subnav file. (You can see it the staged doc here: http://docs-pcf-staging.cfapps.io//partners/dyadic-service-broker/index.html — you can review this staging site today; and put in another PR to make fixes.)
Thanks!

**Comment by dymanuel** [comment]
Thanks Jane! Appreciate your help. Can't log into docs-pcf-staging.

**Comment by jncd** [comment]
Hi Emanuel,
So sorry I missed this email yesterday.
Staging site username and password are pivotalcf and wilderror16
Happy Friday,
jane

On Thu, Mar 9, 2017 at 10:37 AM, Emanuel Fleishman <notifications@github.com

**Comment by dymanuel** [comment]
Hi Jane!
Everything on Production site looks just great, IMO.
Many thanks for walking me through the friendly trenches ☺
Emanuel

**Pull request merged**
